# Add application configuration variables here, as shown below.

TWITTER_API_KEY: PBIPF7qgDLQ4TpTyr0AwA
TWITTER_API_SECRET: vKBVYqaxaUVke4p0UFUQtdIjMZp1RMcfNjC2Z9LyLI
SECRET_KEY_BASE: n438pOrSo2hJLgzWBs8K4lS79qkkw1Uqc6fbyln6lQkAR
